services:
  database:
    image: pgvector/pgvector:pg16
    shm_size: '3gb'
    restart: always
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


networks:
  dokploy-network:
    external: true
