services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/prod.Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RIJKSMUSEUM_API_KEY=${RIJKSMUSEUM_API_KEY}
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sem-art-backend-router-websecure.rule=Host(`semantic-art-api.lockhorst.dev`)"
      - "traefik.http.routers.sem-art-backend-router-websecure.entrypoints=websecure"
      - "traefik.http.routers.sem-art-backend-router-websecure.tls.certResolver=letsencrypt"
      - "traefik.http.services.sem-art-backend-service-websecure.loadbalancer.server.port=8000"
      - "traefik.http.routers.sem-art-backend-router-web.rule=Host(`semantic-art-api.lockhorst.dev`)"
      - "traefik.http.routers.sem-art-backend-router-web.entrypoints=web"
      - "traefik.http.services.sem-art-backend-service-web.middleware=redirect-to-https@file"
      - "traefik.http.services.sem-art-backend-service-web.loadbalancer.server.port=8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/npm.Dockerfile
      args:
        - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
    ports:
      - 4000:4000
    depends_on:
      - backend
    networks:
      - dokploy-network
    volumes:
      - ./frontend-nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sem-art-frontend-router-websecure.rule=Host(`art.lockhorst.dev`)"
      - "traefik.http.routers.sem-art-frontend-router-websecure.centrypoints=websecure"
      - "traefik.http.routers.sem-art-frontend-router-websecure.tls.certResolver=letsencrypt"
      - "traefik.http.services.sem-art-frontend-service-websecure.loadbalancer.server.port=4000"
      - "traefik.http.routers.sem-art-frontend-router-web.rule=Host(`art.lockhorst.dev`)"
      - "traefik.http.routers.sem-art-frontend-router-web.entrypoints=websecure"
      - "traefik.http.services.sem-art-frontend-service-web.middleware=redirect-to-https@file"
      - "traefik.http.services.sem-art-frontend-service-web.loadbalancer.server.port=4000"

networks:
  dokploy-network:
    external: true
