services:
  database:
    image: pgvector/pgvector:pg16
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
