services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/prod.Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RIJKSMUSEUM_API_KEY=${RIJKSMUSEUM_API_KEY}
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.semantic-art-search-backend-web.rule=Host(`semantic-art-api.lockhorst.dev`)
      - traefik.http.routers.semantic-art-search-backend-web.entrypoints=web
      - traefik.http.services.semantic-art-search-backend-web.loadbalancer.server.port=8000
      - traefik.http.routers.semantic-art-search-backend-web.service=semantic-art-search-backend-web
      - traefik.http.routers.semantic-art-search-backend-web.middlewares=redirect-to-https@file
      - traefik.http.routers.semantic-art-search-backend-websecure.rule=Host(`semantic-art-api.lockhorst.dev`)
      - traefik.http.routers.semantic-art-search-backend-websecure.entrypoints=websecure
      - traefik.http.services.semantic-art-search-backend-websecure.loadbalancer.server.port=8000
      - traefik.http.routers.semantic-art-search-backend-websecure.service=semantic-art-search-backend-websecure
      - traefik.http.routers.semantic-art-search-backend-websecure.tls.certresolver=letsencrypt

  frontend:
    build:
      context: .
      dockerfile: ./frontend/prod.Dockerfile
      args:
        - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
    ports:
      - 4000:4000
    depends_on:
      - backend
    networks:
      - dokploy-network
    volumes:
      - ./frontend-nginx.conf:/etc/nginx/nginx.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.semantic-art-search-frontend-web.rule=Host(`art.lockhorst.dev`)
      - traefik.http.routers.semantic-art-search-frontend-web.entrypoints=web
      - traefik.http.services.semantic-art-search-frontend-web.loadbalancer.server.port=4000
      - traefik.http.routers.semantic-art-search-frontend-web.service=semantic-art-search-frontend-web
      - traefik.http.routers.semantic-art-search-frontend-web.middlewares=redirect-to-https@file
      - traefik.http.routers.semantic-art-search-frontend-websecure.rule=Host(`art.lockhorst.dev`)
      - traefik.http.routers.semantic-art-search-frontend-websecure.entrypoints=websecure
      - traefik.http.services.semantic-art-search-frontend-websecure.loadbalancer.server.port=4000
      - traefik.http.routers.semantic-art-search-frontend-websecure.service=semantic-art-search-frontend-websecure
      - traefik.http.routers.semantic-art-search-frontend-websecure.tls.certresolver=letsencryptend-service.loadbalancer.server.port=4000"

networks:
  dokploy-network:
    external: true
