[tool.poetry]
name = "sem-art-search"
version = "0.1.0"
description = ""
authors = ["Sjors Lockhorst <sjors@lockhorst.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
multilingual-clip = "^1.0.10"
clip = {git = "https://github.com/openai/CLIP.git"}
transformers = "^4.41.1"
torch = "^2.3.0"
datasets = "^2.19.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
